name: Deploy frontend to S3

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Account ID: ${{ secrets.AWS_ACCOUNT_ID }}"
          echo "Role: ${{ secrets.DEPLOYMENT_ROLE }}"
          echo "Bucket: ${{ secrets.S3_BUCKET }}"
          echo "Region: ${{ vars.AWS_REGION }}"
          echo "Role: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.DEPLOYMENT_ROLE }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: portfolio/package-lock.json

      - name: Install and build
        run: |
          cd portfolio
          npm ci
          npm run build

      - name: Configure AWS deployment role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.DEPLOYMENT_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync portfolio/out s3://${{ secrets.S3_BUCKET }} --delete
