name: Deploy frontend to S3

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Account ID: ${{ vars.AWS_ACCOUNT_ID }}"
          echo "Role: ${{ vars.DEPLOYMENT_ROLE }}"
          echo "Bucket: ${{ vars.S3_BUCKET }}"
          echo "Region: ${{ vars.AWS_REGION }}"
          echo "Role: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.DEPLOYMENT_ROLE }}"

      - name: Debug OIDC Token
        run: |
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: portfolio/package-lock.json

      - name: Install and build
        run: |
          cd portfolio
          npm ci
          npm run build

      - name: Configure AWS deployment role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.DEPLOYMENT_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync portfolio/out s3://${{ vars.S3_BUCKET }} --delete
